version: '2'


services:
  
  dnsdock:   # remove --verbose later
    image: aacebedo/dnsdock:latest-amd64
    command: --domain dnsdock --environment dev --verbose
    ports:
      - "172.17.0.1:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging: &logging_anchor
      options:
        max-size: "100k"
        max-file: "10"
    
  postgres:
    build:
      context: dockerfiles
      dockerfile: Dockerfile_postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data   # this is the default value
    volumes:
      - /home/alex/mnt/ryctoic/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ryctoic_pgdata:/var/lib/postgresql/data
      # we can't share files here directly, because at the moment of writing docker doesn't allow to map uids in volumes, so we simply copy these files using a copy.sh script
    logging:
      <<: *logging_anchor

  backend:
    build:
      context: dockerfiles
      dockerfile: Dockerfile_backend
    working_dir: /home/theuser/ryctoic
    entrypoint: bash     # was entrypoint: /home/theuser/ryctoic/_rel/hello_world/bin/hello_world     and command: foreground
    volumes:
      - /mnt/vmshared/shared/cowboy/examples/hello_world/:/home/theuser/ryctoic
    ports:
      - "8080:8080"
    logging:
      <<: *logging_anchor


volumes:
  ryctoic_pgdata:
    # external: true


# networks:
#   custom:
#     driver_opts:
#       "com.docker.network.bridge.enable_icc": "false"
    
  
