dnsdock:
    image: tonistiigi/dnsdock
    command: -domain dnsdock -environment dev
    ports:
        - "172.17.0.1:53:53/udp"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    log_driver: "json-file"
    log_opt:
        max-size: "100k"
        max-file: "20"

nginx:   # TODO: this image runs nginx as root, is this a security issue?
    build: dockerfiles_empty_build_context       # image: nginx
    dockerfile: Dockerfile_nginx

    ports:
        - "8443:8443"
    volumes:
        - /home/alex/mnt/ryctoic/nginx.conf:/etc/nginx/nginx.conf:ro
        - /home/alex/mnt/ryctoic/priv/ssl/server.crt:/etc/nginx/server.crt:ro
        - /home/alex/mnt/ryctoic/priv/ssl/server.key:/etc/nginx/server.key:ro
    log_opt:
        max-size: "100k"
        max-file: "20"
    
        
backend:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_backend

    working_dir: /home/theuser/ryctoic
    entrypoint: bin/entrypoint-backend.sh     # was entrypoint: /home/theuser/ryctoic/_rel/hello_world/bin/hello_world     and command: foreground

    volumes:
        - .:/home/theuser/ryctoic
        - ../ryctoic.secrets:/home/theuser/secrets      # see vm's shared dirs

    ports:
        - "8080:8080"
    # expose:
    # we'll have to expose some ports if we need to interconnect erlang nodes 
    #  - "4369:4369"
    #  - "9101:9101"
    #  - "9102:9102"
    #  - "9103:9103"
    #  - "9104:9104"
    #  - "9105:9105"
    log_opt:
        max-size: "100k"
        max-file: "20"

        
figwheel:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_figwheel

    volumes:
        - /home/alex/mnt/ryctoic/:/home/theuser/ryctoic
        # cache dependencies of lein figwheel to avoid downloading them on every run, this is gitignored
        - /home/alex/mnt/ryctoic/client-web/lein-deps:/home/theuser/.m2/

    working_dir: /home/theuser/ryctoic/client-web
    command: /usr/local/bin/lein figwheel
    # command: /bin/true
    # command: while true ; do echo "doing nothing" && sleep 5 ; done

    # stdin_open: true
    # tty: true
    log_opt:
        max-size: "100k"
        max-file: "20"


postgres:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_postgres
    expose:
        - "5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=secret
        - PGDATA=/var/lib/postgresql/data_outside_the_volume_to_start_from_scratch_every_time
        # - PGDATA=/var/lib/postgresql/data   # this is default

    # volumes_from:
    #     - data
    volumes:
        - /home/alex/mnt/ryctoic/sql/init.sh:/docker-entrypoint-initdb.d/init.sh
        - /home/alex/mnt/ryctoic/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        - /home/alex/mnt/ryctoic/sql:/sql
        # we can't share some files here, because at the moment of writing docker doesn't allow to map uids in volumes
        # so we simply copy these files using init.sh

    # entrypoint: /bin/true     # bin/docker-compose.sh run --rm --entrypoint "/docker-entrypoint.sh" pgtest postgres ___please_dont_start___

    # docker exec -it ryctoic_pgtest_run_1 psql --dbname ryctoicdb --user administrator --no-password --file /sql/init.test
    log_opt:
        max-size: "100k"
        max-file: "20"

    
data:
    image: postgres
    # dockerfile: Dockerfile_postgres
    volumes:
        - /var/lib/postgresql
        - /home/alex/mnt/ryctoic/tmp:/mnt
    entrypoint: /bin/true
    log_opt:
        max-size: "100k"
        max-file: "20"


cordova_browser_console_logger:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_cordova_browser_console_logger
    volumes:
        - /home/alex/mnt/ryctoic/bin/cordova_browser_console_logger.py:/home/theuser/cordova_browser_console_logger.py
    command: /home/theuser/cordova_browser_console_logger.py
    log_opt:
        max-size: "100k"
        max-file: "20"

        






