dnsdock:
    image: tonistiigi/dnsdock
    command: -domain dnsdock -environment dev
    ports:
        - 172.17.42.1:53:53/udp
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    

nginx:   # TODO: this image runs nginx as root, is this a security issue?
    # image: nginx
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_nginx

    links:
        - dnsdock
        - backend
        - figwheel
    ports:
        - "8443:8443"
    volumes:
        - nginx.conf:/etc/nginx/nginx.conf:ro
        - priv/ssl/server.crt:/etc/nginx/server.crt:ro
        - priv/ssl/server.key:/etc/nginx/server.key:ro
    
        
backend:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_backend

    working_dir: /home/theuser/ryctoic
    entrypoint: bin/entrypoint.sh     # was entrypoint: /home/theuser/ryctoic/_rel/hello_world/bin/hello_world     and command: foreground

    volumes:
        - .:/home/theuser/ryctoic
        - ../ryctoic.secrets:/home/theuser/secrets      # see vm's shared dirs

    # ports:
    #     - "8080:8080"

    # expose:
    # we'll have to expose some ports if we need to interconnect erlang nodes 
    #  - "4369:4369"
    #  - "9101:9101"
    #  - "9102:9102"
    #  - "9103:9103"
    #  - "9104:9104"
    #  - "9105:9105"

    links:
        - postgres

        
figwheel:
    build: dockerfiles_empty_build_context
    dockerfile: Dockerfile_figwheel

    volumes:
        - .:/home/theuser/ryctoic
        # cache dependencies of lein figwheel to avoid downloading them on every run, this is gitignored
        - ./client-web/lein-deps:/home/theuser/.m2/

    working_dir: /home/theuser/ryctoic/client-web
    command: lein figwheel
    # command: while true ; do echo "doing nothing" && sleep 5 ; done

    # stdin_open: true
    # tty: true


    
postgres:
    image: postgres
    expose:
        - "5432"

    environment:     # TODO: CRITICAL secure postgres docker
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=mysecretpassword3
        # - PGDATA:whatever

    volumes_from:
        - data

    volumes:
        - tmp:/home/theuser/tmp

        
data:
    image: postgres
    dockerfile: Dockerfile_postgres
    volumes:
        - /var/lib/postgresql
        - tmp:/mnt
    entrypoint: true



mongo:
    image: mongo
    
