version: '2'

services:

  dnsdock:
    image: tonistiigi/dnsdock
    command: -domain dnsdock -environment dev
    ports:
      - "172.17.0.1:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "100k"
        max-file: "10"
  

  postgres:
    build:
      context: dockerfiles_empty_build_context
      dockerfile: Dockerfile_postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data   # this is the default value
    volumes:
      - /home/alex/mnt/ryctoic/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ryctoic_pgdata:/var/lib/postgresql/data
      # we can't share files here directly, because at the moment of writing docker doesn't allow to map uids in volumes, so we simply copy these files using a copy.sh script
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    network_mode: "bridge"

  pgtest:   # for testing migrations
    build:
      context: dockerfiles_empty_build_context
      dockerfile: Dockerfile_postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data_outside_the_volume   # this makes pgdata disposable when doing $ docker run --rm
    volumes:
      - /home/alex/mnt/ryctoic/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    logging:
      options:
        max-size: "100k"
        max-file: "10"
    entrypoint: /bin/true
    network_mode: "bridge"



    
volumes:
  ryctoic_pgdata:
    external: true


  
  
