FROM clojure:lein-2.5.1

# at the moment of writing the docker volumes' owner uid is 1000 and can't be changed
RUN groupadd theuser && useradd --create-home --gid theuser --uid 1000 theuser
WORKDIR /home/theuser
# erl needs this to check ~/.erlang:
ENV HOME /home/theuser
USER theuser

# COPY project.clj $HOME/
# RUN lein  deps

