FROM java:openjdk-8u66-jre

RUN groupadd theuser && useradd --create-home --gid theuser --uid 1000 theuser
WORKDIR /home/theuser
USER theuser


# TODO: critical: check signature
RUN wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/3.2.1/flyway-commandline-3.2.1.tar.gz && \
    tar xvfz flyway-commandline-3.2.1.tar.gz && \
    rm flyway-commandline-3.2.1.tar.gz


